defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
disableLanguages = ["en"]
enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

[pagination]
pagerSize = 12

[imaging]
anchor = "Center"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.7

[outputs]
home = ["HTML", "RSS", "JSON"]
